name: provisioning

on:
  push:
  schedule:
    - cron: '1 2 3 * *' # 02:01, 3rd day every month
  workflow_dispatch:

jobs:
  provisioning:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Export UIDs as environment variables
        run: |
          cat<<EOE > .env
          # Todo https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-githubs-ip-addresses
          TF_VAR_allowed_ipaddr_list=["0.0.0.0/0"]
          EOE
          echo "UID=$(id -u)" >> .env
          echo "GID=$(id -g)" >> .env
          echo "DOCKER_GID=$(getent group docker | cut -d : -f 3)" >> .env
      - name: Generate and export Project ID as the environment variable
        run: |
          echo "PROJECT_UNIQUE_ID=${PROJECT_UNIQUE_ID}" >> .env
        env:
          PROJECT_UNIQUE_ID: ${{ secrets.PROJECT_UNIQUE_ID }}
      - name: Export credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> .env
          echo "AWS_ACCOUNT_ID=${AWS_ACCOUNT_ID}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> .env
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: (debug)Check services
        run: |
          docker compose config
      - name: Build containers
        timeout-minutes: 4
        run: |
          docker compose build
      - name: Start the service
        timeout-minutes: 1
        run: |
          docker compose up --detach
      - name: Check the service health
        timeout-minutes: 4
        run: |
          while :
          do
            docker compose ps --format=json provisioning\
             | jq -e 'select(.Health=="healthy")' 2> /dev/null\
             && break
            sleep 1
          done
      - name: Show service logs
        timeout-minutes: 1
        run: |
          docker compose logs
      - name: Exec Terraform - check the format for each tf file
        run: |
          docker compose exec provisioning terraform fmt -check -recursive
      - name: Exec Terraform - validate
        run: |
          docker compose exec provisioning terraform validate
      - name: Exec Terraform - dry-run
        continue-on-error: true
        timeout-minutes: 1
        run: |
          docker compose exec provisioning zsh -lc 'terraform plan & terraform plan'
      - name: Stop the service
        timeout-minutes: 1
        run: |
          docker compose down
